# Generated by Django 5.2.10 on 2026-01-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.ImageField(upload_to='comment/images/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
