# Generated by Django 5.2.10 on 2026-02-02 12:50

from django.db import migrations

data = [
    {
        "title": "کالای الکترونیک",
        "subcategories": [
            "موبایل",
            "لپ تاپ",
            "دسته بازی"
        ]
    },
    {
        "title": "پوشاک",
        "subcategories": [
            "پیراهن",
            "شلوار"
        ]
    }
]


def create_initial_category(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    SubCategory = apps.get_model('category', 'SubCategory')

    for category in data:
        category_obj = Category.objects.create(title=category['title'])
        for subcategory_title in category['subcategories']:
            SubCategory.objects.create(
                title=subcategory_title,
                category=category_obj
            )


def delete_initial_category(apps, schema_editor):
    Category = apps.get_model('category', 'Category')

    for category in data :
        Category.objects.get(title=category['title']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_category,
            reverse_code=delete_initial_category,
        )
    ]
