# Generated by Django 5.2.10 on 2026-02-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_add_initial_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
