# Generated by Django 5.2.10 on 2026-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productfeature_id_alter_productimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_comments',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Summary Comments'),
        ),
    ]
