# Generated by Django 5.2.10 on 2026-02-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options_alter_subcategory_options'),
        ('product', '0003_product_score_product_summary_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.subcategory', verbose_name='Category'),
        ),
    ]
