# Generated by Django 6.0 on 2026-01-05 09:37

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('manage_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
