# Generated by Django 5.2.10 on 2026-01-10 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('items', models.JSONField(default=dict, verbose_name='Items')),
                ('status', models.CharField(choices=[('in_market', 'In market'), ('warehouse', 'Warehouse'), ('broadcast', 'Broadcast'), ('post_office', 'Post Office'), ('post_officer', 'Post Officer'), ('received', 'Received'), ('canceled', 'Canceled')], default='in_market', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_info', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['-created_at'], name='cart_cartin_created_53fd51_idx'), models.Index(fields=['status'], name='status_index'), models.Index(fields=['amount'], name='amount_index'), models.Index(fields=['user'], name='user_index')],
            },
        ),
    ]
