# Generated by Django 6.0 on 2025-12-26 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=11, verbose_name='Mobile Number')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('province', models.CharField(max_length=30, verbose_name='Province')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Market Request',
                'verbose_name_plural': 'Market Requests',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['-created_at'], name='market_requ_created_94b0f1_idx'), models.Index(fields=['city'], name='market_requ_city_a50026_idx')],
            },
        ),
    ]
