# Generated by Django 6.0 on 2026-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrequest',
            name='national_code',
            field=models.CharField(default=1, max_length=10, verbose_name='National Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketrequest',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
    ]
