# Generated by Django 6.0 on 2026-01-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_request', '0002_marketrequest_national_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrequest',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Age'),
            preserve_default=False,
        ),
    ]
