# Generated by Django 6.0 on 2026-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_request', '0003_marketrequest_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrequest',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
