# Generated by Django 6.0 on 2026-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_request', '0004_marketrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrequest',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pd', 'Passed'), ('rj', 'Rejected')], default='df', max_length=2, verbose_name='Status'),
        ),
    ]
