# Generated by Django 6.0 on 2025-12-19 08:44

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_marketer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=['center', 'middle'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[500, 500], upload_to='market/icons')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('number_phone_1', models.CharField(blank=True, max_length=11, null=True)),
                ('number_phone_2', models.CharField(blank=True, max_length=11, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='user.marketer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['-created_at'], name='market_mark_created_cb7f1b_idx')],
            },
        ),
    ]
