# Generated by Django 6.0 on 2026-01-05 09:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_market_id'),
        ('user', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='market',
            name='market_mark_created_cb7f1b_idx',
        ),
        migrations.AlterField(
            model_name='market',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[500, 500], upload_to='market/icons'),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('marketer', 'name')},
        ),
    ]
