# Generated by Django 6.0 on 2026-01-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_market_options_and_more'),
        ('user', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['-created_at'], name='market_mark_created_cb7f1b_idx'),
        ),
    ]
