# Generated by Django 6.0 on 2026-01-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_market_options_and_more'),
        ('user', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['name'], name='market_mark_name_a6c92f_idx'),
        ),
    ]
