# Generated by Django 5.2.10 on 2026-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_market_market_mark_name_a6c92f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
