# Generated by Django 6.0 on 2026-01-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_marketer_user_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
