# Generated by Django 6.0 on 2026-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketer',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketer',
            name='city',
            field=models.CharField(default=1, max_length=30, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketer',
            name='national_code',
            field=models.CharField(default=1, max_length=10, verbose_name='National Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketer',
            name='province',
            field=models.CharField(default=1, max_length=30, verbose_name='Province'),
            preserve_default=False,
        ),
    ]
