# Generated by Django 5.2.10 on 2026-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_marketer_id_alter_otp_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
