# Generated by Django 6.0 on 2025-12-22 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='Mobile Number')),
                ('final_price', models.PositiveIntegerField(verbose_name='Final Price')),
                ('description', models.JSONField(verbose_name='Description')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at', 'is_paid'],
                'abstract': False,
                'indexes': [models.Index(fields=['-created_at'], name='transaction_created_fc4c1b_idx'), models.Index(fields=['is_paid'], name='is_paid'), models.Index(fields=['mobile_number'], name='mobile_number')],
            },
        ),
    ]
