# Generated by Django 6.0 on 2025-12-22 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_is_paid_871a8c_idx',
            old_name='is_paid',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_mobile__0cdae6_idx',
            old_name='mobile_number',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['first_name', 'last_name'], name='transaction_first_n_23bb27_idx'),
        ),
    ]
